### ISSUE TITLE
Reuse styles from vscode-glimmer-syntax

### ISSUE THREAD

**Issue by lifeart** [chiragpat/vscode-glimmer#1]
Hi @chiragpat!

I like how you extension implement syntax highlighting for `.js/.ts` files!
I have new `.hbs` syntax highlighting addon, and trying to figure out, how we can cooperate and use same syntax highlighting or kinda.

https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-glimmer-syntax

**Comment by chiragpat** [comment]
@lifeart Happy to integrate your language extension into this extension. I am new to vscode extensions is there anyway I can just reference your extension in mine so that it installs yours with mine almost like a dependency? or were you suggesting merging our 2 repositories?

**Comment by lifeart** [comment]
I like how you dealing with `js/ts` inegraion (whout full syntax reexport)  comparing https://marketplace.visualstudio.com/items?itemName=dhedgecock.ember-syntax https://github.com/healthsparq/vscode-ember-syntax/tree/master/syntaxes 

I wondering it is possible to reuse addon as dependency to highliht syntax (could you test it?)

In ower case - we can merge functionality, create organization and support it.

One more option - we can create "syntax" repo, like https://github.com/healthsparq/glimmer-syntax-patterns and reuse it in both implementations.

What do you think?

**Comment by lifeart** [comment]
copying `inline-hbs.json` and scope name alignment fixes ts/js highlighting in my addon! Thank you so much for such elegant js/ts syntax injection logic!
